# Generated by Django 2.1.7 on 2021-10-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_condition_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userAccount.Task'),
        ),
        migrations.AddField(
            model_name='condition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userAccount.User'),
        ),
    ]
