# Generated by Django 2.1.7 on 2021-10-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_auto_20211010_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='name',
        ),
    ]
